name: gaia-smoke

on:
  workflow_dispatch: {}
  # optionnel si tu veux un test hebdo :
  # schedule:
  #   - cron: "0 6 * * 1"

jobs:
  gaia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Gaia run (small)
        run: |
          python workflow.py gaia --ra 266.4051 --dec -28.936175 --radius-deg 0.2 --limit 300 --out results/ci_gaia --plots --explain-top 3 --top-k 20

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: gaia-ci
          path: results/ci_gaia
